### ISSUE TITLE
"No module named graph_cpu" error

### ISSUE THREAD

**Issue by aajanqd** [chrsmrrs/k-gnn#12]
When running 1-2-3-proteins.py, I got the following error: 

Traceback (most recent call last):
  File "1-2-3-proteins.py", line 9, in <module>
    from k_gnn import DataLoader, GraphConv, avg_pool
  File "/scratch/aqd215/k-gnn/examples/k_gnn/__init__.py", line 1, in <module>
    from graph_cpu import two_local, connected_two_local
ModuleNotFoundError: No module named 'graph_cpu'

Not sure how to resolve this.
Thanks!

**Comment by alorozco53** [comment]
Same situation as above. 

Running on `torch` version 1.5.1, Ubuntu 20.04, under a `virtualenv`

**Comment by aajanqd** [comment]
@alorozco53 did you find a way to fix this?

**Comment by chrsmrrs** [comment]
We developed it for PyG 1.4 and Torch 1.4. I do not have the time to update it with every new version.

**Comment by rusty1s** [comment]
I tested the current code with PyTorch 1.6.0 and PyG 1.6.1 and can not reproduce the above issue. This is definitively not PyTorch or PyG related.

IMO, the above error occurs since the C++ modules could not be found, so I suggest running
```
rm -rf build && python setup.py install
```
and look for any errors that might occur during installation.

**Comment by aajanqd** [comment]
Resolved by running `python setup.py install`. Forgot to do this when setting everything up.
