### ISSUE TITLE
Running models on other datasets in similar domain

### ISSUE THREAD

**Issue by trinayan** [chrsmrrs/k-gnn#13]
Hi,

I was trying to run other datasets from the TU dataset like the facebook_ct1, github_stargazer etc. I tried just using the same code from examples/1-2-3-imdb.py and replaced the datasets with others. It seems like the code is tied to a specific dataset. Can you provide some high level guidance on how to get the code working for other datasets?. for example to get the imbd code working with facebook dataset?. Thanks

**Comment by rusty1s** [comment]
The code is tied to common benchmark datasets. For example, `facebook_ct1` is a temporal dataset that currently cannot be read by PyTorch Geometric. I looked into `github_stargazer` and assume that this one should work, but you need to add (synthetic) node features since they are not initially provided, *e.g.*, via `torch_geometric.transforms.OneHotDegree`.
