### ISSUE TITLE
MAE question

### ISSUE THREAD

**Issue by jwzhi** [chrsmrrs/k-gnn#8]
Hi, when running your code, it has both Test MAE and Test MAE norm, I wonder which one is the one that you used in your paper?

**Comment by muhanzhang** [comment]
I believe they are reporting the Test MAE instead of Test MAE norm, which aligned with my experimental results. By the way, in the latest QM9 dataset provided by PyG, many tasks' units have been changed, e.g., task 2 (HOMO)'s unit was changed from Hartree to ev, see [here](https://github.com/rusty1s/pytorch_geometric/commit/09e4c8cb16e46a74dfcd4af9cd8354bbfd47bbd3). But the original paper reported task 2's MAE in Hartree. Thus, do remember to manually convert the results back when comparing with the paper.

**Comment by chrsmrrs** [comment]
@muhanzhang is right.
